# Generated by Django 4.2 on 2023-04-09 13:01

import core.models
import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_phone_num_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, validators=[core.models.check_birth_date], verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, validators=[core.validators.censored_title], verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator(allowlist=['mail.ru', 'yandex.ru'], message='Регистрация с данного домена запрещена.')], verbose_name='эл.почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, validators=[core.validators.validate_password], verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
    ]
