# Generated by Django 4.2 on 2023-04-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
